name: dorun_app_flutter
description: "Dorun App Flutter"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localization: ^0.2.0
  intl: ^0.18.1
  cupertino_icons: ^1.0.6
  dio: ^5.4.1
  flutter_secure_storage: ^9.0.0
  json_annotation: ^4.8.1
  retrofit: ^4.1.0
  logger: ^2.1.0
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  skeletonizer: ^1.1.0
  go_router: ^13.2.0
  badges: ^3.1.2
  uuid: ^4.3.3
  debounce_throttle: ^2.0.0
  percent_indicator: ^4.0.1
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  retrofit_generator: ^8.1.0
  mockito: ^5.4.4


flutter:
  uses-material-design: true

  # assets:
    # - asset/images/
    # - asset/images/background/
    # - asset/images/character/
    # - asset/images/group/
    # - asset/images/item/
    # - asset/images/login/
    # - asset/images/profile/
    # - asset/lottie/
    # - asset/main_bgm.wav

  fonts:
    - family: NotoSans
      fonts:
        - asset: asset/fonts/NotoSansKR-Black.ttf
          weight: 900
        - asset: asset/fonts/NotoSansKR-Bold.ttf
          weight: 700
        - asset: asset/fonts/NotoSansKR-Medium.ttf
          weight: 500
        - asset: asset/fonts/NotoSansKR-Regular.ttf
          weight: 400
        - asset: asset/fonts/NotoSansKR-Light.ttf
          weight: 300
        - asset: asset/fonts/NotoSansKR-Thin.ttf
          weight: 100
    - family: TossFace
      fonts:
      - asset: asset/fonts/TossFaceFontMac.ttf
